### ISSUE TITLE
rails server don't work

### ISSUE THREAD

**Issue by MichaelGajda** [iboard/CBA#6]
Hi,
i just tried your CBA because i like the easyness of installation and configuration.
The setup routine runned smoothly, i configured everything and then wanted to start the server:
``` root@lvpsxxxxxxx:/var/www/vhosts/newsite# rails server

``````

This is the result:
``` /usr/local/bin/rails: line 9: require: command not found
 /usr/local/bin/rails: line 11: version: command not found
 /usr/local/bin/rails: line 13: syntax error near unexpected token `('
 /usr/local/bin/rails: line 13: `if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then'
``````

I'm on Ubunto 10.04 server, rails 3.0.7 and ruby 1.9.2.

Do you know what this is?

**Comment by iboard** [comment]
Hi Michael,

it seems 'rails' is executed by bash instead of ruby. Do `which rails` and take a look at the very first line. It should be something like `#!/Users/developer/.rvm/rubies/ruby-1.9.2-p180/bin/ruby` 

I guess there is something wrong with your rails-installation.
I recommend not to run the server as user 'root' and you should take a look at 'rvm' the ruby-version-manager.

cheers
- Andreas
